synctesters:
  local:
    chain_id: 2151908
    el_rpc: http://localhost:65293/
  sepolia:
    chain_id: 11155420
    el_rpc: https://sepolia.optimism.io
  mainnet:
    chain_id: 10
    el_rpc: https://mainnet.optimism.io
